name: 'Generate error log'

runs:
  using: "composite"
  steps:
    - name: Generate error logs
      if: ${{ !cancelled() }}
      run: |
        : Generate error logs
        ./konflux-ci/generate-err-logs.sh
        cp -r artifacts logs
      shell: bash

    - name: Archive logs
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs
