name: 'Retrigger Workflow'

on:
  issue_comment:
    types: [created]

jobs:
  retrigger-pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Echo it back baby
        if: ${{ contains(toLower(github.event.comment.body), '/retrigger') }}
        run: "retrigger!!!"

      - name: Run if comment does NOT include /retrigger
        if: ${{ !contains(toLower(github.event.comment.body), '/retrigger') }}
        run: echo "No /retrigger found ❌"