name: Retrigger Workflow

on:
  issue_comment:
    types: [created]

jobs:
  retrigger-pr-check:
    runs-on: ubuntu-latest
    steps:
      name: Echo it back baby
      run: echo ${{ github.event.comment.body }}