name: 'Retrigger Workflow'

on:
  issue_comment:
    types: [created]

jobs:
  retrigger-pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Retrigger Workflow
        env:
          COMMENT: ${{ github.event.comment.body }}
          #PR_BRANCH: ${{ github.event.issue.pull_request.head.ref }}
        run: |
          COMMENT_LOWER=$(echo "$COMMENT" | tr '[:upper:]' '[:lower:]')

          echo "$COMMENT_LOWER"

          if [[ "$COMMENT_LOWER" == /retrigger* ]]; then
            echo "command present, checking for target."

            TARGET=$(echo "$COMMENT_LOWER" | awk '{print $2}')

            if [[ -z "$TARGET" ]]; then
              echo "No specific workflow specified. Triggering all workflows..."
              #echo "## Add more dispatches below as needed"

              #gh workflow run workflow1.yml --ref "$PR_BRANCH"
              #gh workflow run workflow2.yml --ref "$PR_BRANCH"
            else
              echo "Triggering workflow: $TARGET.yaml"
              #gh workflow run "$TARGET.yaml" --ref "$PR_BRANCH"
            fi
          else
            echo "No retrigger command found."
          fi

        shell: bash