name: 'Retrigger Workflows'

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: read

jobs:
  retrigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Retrigger Workflows
        env:
          COMMENT: ${{ github.event.comment.body }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #PR_BRANCH: ${{ github.event.issue.pull_request.head.ref }}
        run: |
          COMMENT_LOWER=$(echo "$COMMENT" | tr '[:upper:]' '[:lower:]')
          echo "Message: $COMMENT"

          if [[ "$COMMENT_LOWER" != /retrigger* ]]; then
            echo "No /retrigger command found."
            exit 0
          fi

          echo "command present, checking for target"
          TARGET=$(echo "$COMMENT_LOWER" | awk '{print $2}')

          if [[ -z "$TARGET" ]]; then
            echo "No specific workflow specified. Triggering all workflows"

            exit 0
          fi

          echo "Triggering workflow: $TARGET.yaml"

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/$TARGET.yaml/dispatches \
            -d '{"ref":"main"}'

        shell: bash


# maybe add the ability to trigger multiple selected files:
# /retrigger workflow1 workflow2 ...

# check if target.yaml exists
# run it somehow -> calcel if not finished?